# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f449846ad70642408152c9322dc033651d768d0a778c848926038b7424c49d5b483d9d433a60ad3be5f3891ea7c70bd6f9c4d0833037010fd89567f921ca2d

test:
  secret_key_base: aa9f395539509bc40983cf2d2a3bd8201a719baec7089a62c40279df0097db0a5926e7892215367d874a20a9c45c0a2088af657c01688cb8bd7f26598945d949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
